Xact DEFINITIONS AUTOMATIC TAGS ::=
BEGIN

XactReqHeader ::= SEQUENCE {
    hash OCTET STRING SIZE (64),
    len INTEGER
}

XactBatchHeader ::= SEQUENCE {
    seqnum INTEGER,
    nreqs INTEGER (0..16777215)
}

END